image:
- Visual Studio 2015

before_build:
  - cmd: mkdir ..\build
  - cmd: cd ..\build
  - cmd: cmake ..\cpp00

build:
  project: ..\build\cpp00.sln
  parallel: true
  #verbosity: quiet

after_build:
  - cmd: 7z a build.7z ..\build

artifacts:
  - path: .\build.7z
